import { appendFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "supabase-aartis-seed.sql");

const aartis = [
  { slug:"lavathavati-vikrala-shiv", title:"Lavathavati Vikrala", title_devanagari:"लावथवती विक्राळा", deity:"Shiva", category:"shiva", language:"marathi", type:"aarti", description:"Marathi Shiv Aarti - Karpurgaura", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:21, lyrics:"लवथवती विक्राळा ब्रह्मांडी माळा।\nवीषें कंठ काळा त्रिनेत्रीं ज्वाळा॥\n\nलावण्यसुंदर मस्तकी बाळा।\nतेथुनियां जळ निर्मळ वाहे झुळझुळा॥\n\nजय देव जय देव जय श्री शंकरा।\nआरती ओवाळूं तुज कर्पूरगौरा॥\n\nकर्पूरगौरा भोळा नयनीं विशाळा।\nअर्धांगी पार्वती सुमनांच्या माळा॥\n\nविभुतीचें उधळण शितिकंठ नीळा।\nऐसा शंकर शोभे उमावेल्हाळा॥\n\nजय देव जय देव जय श्री शंकरा।\nआरती ओवाळूं तुज कर्पूरगौरा॥\n\nदेवीं दैत्यीं सागरमंथन पै केलें।\nत्यामाजीं अवचित हळाहळ उठिलें॥\n\nतें त्वां असुरपणें प्राशन केलें।\nनीलकंठ नाम प्रसिद्ध झालें॥\n\nजय देव जय देव जय श्री शंकरा।\nआरती ओवाळूं तुज कर्पूरगौरा॥\n\nव्याघ्रांबर फणिवरधर सुंदर मदनारी।\nपंचानन मनमोहन मुनिजनसुखकारी॥\n\nशतकोटींचें बीज वाचे उच्चारी।\nरघुकुळटिळक रामदासा अंतरी॥\n\nजय देव जय देव जय श्री शंकरा।\nआरती ओवाळूं तुज कर्पूरगौरा॥" },
  { slug:"trigunatmak-trimurti-datta", title:"Trigunatmak Trimurti Datta", title_devanagari:"त्रिगुणात्मक त्रैमूर्ती दत्त", deity:"Dattatreya", category:"dattatreya", language:"marathi", type:"aarti", description:"Marathi Dattatreya Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:22, lyrics:"त्रिगुणात्मक त्रैमूर्ती दत्त हा जाणा।\nत्रिगुणी अवतार त्रैलोक्यराणा॥\n\nनेति नेति शब्दें न ये अनुमाना।\nसुरवर मुनिजन योगी समाधि न ध्याना॥\n\nजय देव जय देव जय श्री गुरुदत्ता।\nआरती ओवाळिता हरली भवचिंता॥\n\nसबाह्य अभ्यंतरी तू एक दत्त।\nअभाग्यासी कैची कळेल ही मात॥\n\nपराही परतली तेथे कैचा हेत।\nजन्ममरणाचा पुरलासे अंत॥\n\nजय देव जय देव जय श्री गुरुदत्ता।\nआरती ओवाळिता हरली भवचिंता॥\n\nदत्त येऊनिया उभा ठाकला।\nसद्भावे साष्टांगे प्रणिपात केला॥\n\nप्रसन्न होऊनि आशीर्वाद दिधला।\nजन्ममरणाचा फेरा चुकविला॥\n\nजय देव जय देव जय श्री गुरुदत्ता।\nआरती ओवाळिता हरली भवचिंता॥" },
  { slug:"ovalu-aarti-madan-gopala", title:"Ovalu Aarti Madan Gopala", title_devanagari:"ओवाळू आरती मदनगोपाळा", deity:"Krishna", category:"krishna", language:"marathi", type:"aarti", description:"Marathi Krishna Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:23, lyrics:"ओवाळू आरती मदनगोपाळा।\nश्यामसुंदर गळां वैजयंतीमाळा॥\n\nचरणकमळीं नूपुर वाजती रुणझुणा।\nकटितटि पीतांबर शोभे नारायणा॥\n\nओवाळू आरती मदनगोपाळा॥\n\nमोरमुकुट माथां कुंडले श्रवणी।\nमुखकमळीं मुरली विराजे करणी॥\n\nओवाळू आरती मदनगोपाळा॥\n\nगोपीजनवल्लभ नंदाचा बाळा।\nयशोदेच्या अंगणी खेळे गोपाळा॥\n\nओवाळू आरती मदनगोपाळा॥" },
  { slug:"sri-ramachi-aarti", title:"Sri Ramachi Aarti", title_devanagari:"श्री रामाची आरती", deity:"Rama", category:"ram", language:"marathi", type:"aarti", description:"Marathi Ram Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:24, lyrics:"त्रिभुवनमंडितमाळ गळां।\nआरती ओवाळूं पाहूं ब्रह्मपुतळा॥\n\nश्रीराम जय राम जय जय राम।\nआरती ओवाळूं पाहूं सुंदर मेघश्यामा॥\n\nश्रीराम जय राम जय जय राम॥\n\nकौसल्येचा राम, दशरथाचा बाळ।\nअयोध्येचा राजा, भक्तांचा प्रतिपाळ॥\n\nश्रीराम जय राम जय जय राम॥\n\nसीताराम लक्ष्मण हनुमंता।\nचरणी ठेवितो माथा॥\n\nश्रीराम जय राम जय जय राम॥" },
  { slug:"ambe-tu-hai-jagdambe-kali", title:"Ambe Tu Hai Jagdambe Kali", title_devanagari:"अंबे तू है जगदंबे काली", deity:"Durga", category:"devi", language:"hindi", type:"aarti", description:"Popular Jagdambe/Durga Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:25, lyrics:"अम्बे तू है जगदम्बे काली,\nजय दुर्गे खप्पर वाली,\nतेरे ही गुण गावें भारती,\nओ मैया हम सब उतारे तेरी आरती।\n\nतेरे भक्त जनो पर माता भीर पड़ी है भारी।\nदानव दल पर टूट पडो माँ करके सिंह सवारी॥\nसौ-सौ सिहों से बलशाली, है अष्ट भुजाओं वाली,\nदुष्टों को तू ही ललकारती।\nओ मैया हम सब उतारे तेरी आरती।\n\nमाँ-बेटे का है इस जग मे बडा ही निर्मल नाता।\nपूत-कपूत सुने है पर ना माता सुनी कुमाता॥\nसब पे करूणा दर्शाने वाली, अमृत बरसाने वाली,\nदुखियों के दुखडे निवारती।\nओ मैया हम सब उतारे तेरी आरती।\n\nनहीं मांगते धन और दौलत, न चांदी न सोना।\nहम तो मांगें तेरे चरणों में छोटा सा कोना॥\nसबकी बिगड़ी बनाने वाली, लाज बचाने वाली,\nसतियों के सत को सवांरती।\nओ मैया हम सब उतारे तेरी आरती।\n\nचरण शरण में खड़े तुम्हारी, ले पूजा की थाली।\nवरद हस्त सर पर रख दो माँ संकट हरने वाली॥\nमाँ भर दो भक्ति रस प्याली, अष्ट भुजाओं वाली,\nभक्तों के कारज तू ही सारती।\nओ मैया हम सब उतारे तेरी आरती।" },
  { slug:"mahalakshmi-aarti", title:"Mahalakshmi Aarti", title_devanagari:"महालक्ष्मी आरती", deity:"Lakshmi", category:"devi", language:"marathi", type:"aarti", description:"Marathi Mahalakshmi Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:26, lyrics:"जय देवी जय देवी जय महालक्ष्मी।\nवससी व्यापकरूपे तू स्थूलसूक्ष्मी॥\n\nकरवी संकटवारी।\nकरुणेची सागर माता॥\n\nजय देवी जय देवी जय महालक्ष्मी॥\n\nकमळावरती बैसूनि, शोभसी माते।\nचतुर्भुज धारण करूनि, वरद हस्ते॥\n\nअभय देसी भक्तांना।\nसंपत्ती देसी नित्य॥\n\nजय देवी जय देवी जय महालक्ष्मी॥\n\nधनधान्याची वृद्धी होवो।\nसुखशांती घरामाजी॥\n\nतुझी कृपा राहो माता।\nसर्व भक्तांवरी॥\n\nजय देवी जय देवी जय महालक्ष्मी॥" },
  { slug:"saraswati-mata-aarti", title:"Saraswati Mata Aarti", title_devanagari:"सरस्वती माता आरती", deity:"Saraswati", category:"devi", language:"hindi", type:"aarti", description:"Saraswati Mata Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:27, lyrics:"जय सरस्वती माता।\nमैया जय सरस्वती माता॥\n\nसद्गुण वैभव शालिनी।\nत्रिभुवन विख्याता॥\n\nजय सरस्वती माता॥\n\nचंद्रवदनी पद्मासिनी।\nद्युतिमंगलकारी॥\n\nसोहे शुभ हंस सवारी।\nअतुल तेजधारी॥\n\nजय सरस्वती माता॥\n\nबाएं कर में वीणा।\nदाएं कर माला॥\n\nशीश मुकुट मणि सोहे।\nगल मोतियन माला॥\n\nजय सरस्वती माता॥\n\nदेवी शरण जो आए।\nउनका उद्धार करो॥\n\nज्ञान प्रकाश भरो माता।\nअज्ञान अंधकार हरो॥\n\nजय सरस्वती माता॥" },
  { slug:"jayati-jayati-jagdambe-mata", title:"Jayati Jayati Jagdambe Mata", title_devanagari:"जयति जयति जगदंबे माता", deity:"Jagdambe", category:"devi", language:"hindi", type:"aarti", description:"Jagdambe Mata Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:28, lyrics:"जयति जयति जगदंबे माता।\nजयति जयति जगदंबे॥\n\nदीनन की तू दीनदयाला।\nभक्तन की प्रतिपाला॥\n\nजयति जयति जगदंबे॥\n\nसिंह सवारी करके माता।\nदुष्टन को संहारा॥\n\nमहिषासुर को मार गिराया।\nदेवन को सुखदायी॥\n\nजयति जयति जगदंबे॥\n\nजो कोई तेरी शरण में आवे।\nमनवांछित फल पावे॥\n\nदुःख संकट सब दूर भगावे।\nमाता कृपा बरसावे॥\n\nजयति जयति जगदंबे॥" },
  { slug:"pandurangachi-aarti", title:"Pandurangachi Aarti", title_devanagari:"पांडुरंगाची आरती", deity:"Vitthal", category:"vitthal", language:"marathi", type:"aarti", description:"Short Pandurang/Vitthal Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:29, lyrics:"पंढरीनाथा विठ्ठला।\nरखुमाईच्या वल्लभा॥\n\nभक्तजनांच्या संकटी।\nधाव घेसी पांडुरंगा॥\n\nजय देव जय देव जय पांडुरंगा।\nरखुमाईच्या वल्लभा॥\n\nकटीवरती हात ठेवुनी।\nविटेवरी उभा राहसी॥\n\nदीनानाथा दयाघना।\nभक्तांवरी कृपा करसी॥\n\nजय देव जय देव जय पांडुरंगा॥" },
  { slug:"dnyanadevachi-aarti", title:"Dnyanadevachi Aarti", title_devanagari:"ज्ञानदेवाची आरती", deity:"Dnyaneshwar", category:"vitthal", language:"marathi", type:"aarti", description:"Aarti of Sant Dnyaneshwar", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:30, lyrics:"आरती ज्ञानराजा।\nमहाकैवल्यतेजा॥\n\nसेविती साधुसंत।\nमनु वेधला माझा॥\n\nआरती ज्ञानराजा॥\n\nलोपले ज्ञान जगी।\nहित नेणती कोणी॥\n\nअवतार पांडुरंग।\nनाम ठेविले ज्ञानी॥\n\nआरती ज्ञानराजा॥\n\nकनकाचे ताट करी।\nउभ्या गोपिका नारी॥\n\nनारद तुंबर हो।\nसाम गाती गायन करी॥\n\nआरती ज्ञानराजा॥\n\nप्रकट गुह्य बोले।\nविश्व ब्रह्म केले॥\n\nराम जनार्दनी।\nपायी मस्तक ठेविले॥\n\nआरती ज्ञानराजा॥" },
  { slug:"tukaramachi-aarti", title:"Tukaramachi Aarti", title_devanagari:"तुकारामाची आरती", deity:"Tukaram", category:"vitthal", language:"marathi", type:"aarti", description:"Aarti of Sant Tukaram", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:31, lyrics:"आरती तुकारामा।\nस्वामी सद्गुरुधामा॥\n\nसच्चिदानंद मूर्ती।\nपाय दाखवी आम्हां॥\n\nआरती तुकारामा॥\n\nराघवाचा दास।\nभक्तीचा प्रकाश॥\n\nनामघोषे दुमदुमले।\nपावन झाले आकाश॥\n\nआरती तुकारामा॥\n\nविठ्ठल नामाचा गजर।\nअखंड चालला स्वर॥\n\nतुका म्हणे पांडुरंगा।\nतुझ्या चरणी माझा ठाव॥" },
  { slug:"niropachi-aarti", title:"Niropachi Aarti", title_devanagari:"निरोपाची आरती", deity:"Ganpati", category:"ganpati", language:"marathi", type:"nirop", description:"Ganpati Visarjan Nirop Aarti - farewell prayer", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:32, lyrics:"घालीन लोटांगण तुझ्या चरणांसी।\nआता निरोप देतो भक्तिभावेंसी॥\n\nपुढल्या वर्षी लवकर या।\nगणपती बाप्पा मोरया॥\n\nमंगलमूर्ती मोरया।\nपुढच्या वर्षी लवकर या॥\n\nसुखकर्ता दुःखहर्ता।\nवार्ता विघ्नाची॥\n\nतुझ्या कृपेने बाप्पा।\nसर्व संकटे टळती॥\n\nगणपती बाप्पा मोरया।\nपुढच्या वर्षी लवकर या॥" },
  { slug:"sri-dattachi-aarti-dup", title:"Sri Dattachi Aarti", title_devanagari:"श्री दत्ताची आरती", deity:"Dattatreya", category:"dattatreya", language:"marathi", type:"aarti", description:"Another version of Dattatreya Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:33, lyrics:"त्रिगुणात्मक त्रैमूर्ती दत्त हा जाणा।\nत्रिगुणी अवतार त्रैलोक्यराणा॥\n\nनेति नेति शब्दें न ये अनुमाना।\nसुरवर मुनिजन योगी समाधि न ध्याना॥\n\nजय देव जय देव जय श्री गुरुदत्ता।\nआरती ओवाळिता हरली भवचिंता॥\n\nसबाह्य अभ्यंतरी तू एक दत्त।\nअभाग्यासी कैची कळेल ही मात॥\n\nपराही परतली तेथे कैचा हेत।\nजन्ममरणाचा पुरलासे अंत॥\n\nजय देव जय देव जय श्री गुरुदत्ता॥" },
  { slug:"sri-marutichi-aarti", title:"Sri Marutichi Aarti", title_devanagari:"श्री मारुतीची आरती", deity:"Hanuman", category:"hanuman", language:"marathi", type:"aarti", description:"Marathi Hanuman/Maruti Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:34, lyrics:"सत्राणे उड्डाणे हुंकार वदनी।\nकरी डळमळ भूमंडळ सिंधूजळ गगनी॥\n\nकडाडिले ब्रह्मांड धाके त्रिभुवनी।\nसुरवर नर निशाचर त्या झाल्या पळणी॥\n\nजय देव जय देव जय हनुमंता।\nतुमचेनि प्रतापे न भिये कृतांता॥\n\nदुमदुमली पाताळे उठिला प्रतिशब्द।\nथरथरला धरणीधर मानीला खेद॥\n\nकडकडिले पर्वत उडुगण उच्छेद।\nरामी रामदासा शक्तीचा शोध॥\n\nजय देव जय देव जय हनुमंता॥" },
  { slug:"ganpati-atharvashirsha", title:"Ganpati Atharvashirsha", title_devanagari:"गणपती अथर्वशीर्ष", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"stotra", description:"Ganesh Atharvashirsha Upanishad", source:"Atharva Veda", content_status:"needs_verification", verified:false, published:true, sort_order:35, lyrics:"ॐ नमस्ते गणपतये।\nत्वमेव प्रत्यक्षं तत्त्वमसि।\nत्वमेव केवलं कर्ताऽसि।\nत्वमेव केवलं धर्ताऽसि।\nत्वमेव केवलं हर्ताऽसि।\nत्वमेव सर्वं खल्विदं ब्रह्मासि।\nत्वं साक्षादात्मासि नित्यम्॥\n\nऋतं वच्मि। सत्यं वच्मि॥\n\nअव त्वं माम्।\nअव वक्तारम्।\nअव श्रोतारम्।\nअव दातारम्।\nअव धातारम्।\nअवानूचानमव शिष्यम्॥\n\nसर्वतो मां पाहि पाहि समन्तात्॥\n\nत्वं वाङ्मयस्त्वं चिन्मयः।\nत्वमानन्दमयस्त्वं ब्रह्ममयः।\nत्वं सच्चिदानन्दाद्वितीयोऽसि॥\n\nत्वं प्रत्यक्षं ब्रह्मासि।\nत्वं ज्ञानमयो विज्ञानमयोऽसि॥" },
  { slug:"ganesh-stotra", title:"Ganesh Stotra", title_devanagari:"गणेश स्तोत्र", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"stotra", description:"Ganesh Stotra with Vakratunda and Ekadantam", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:36, lyrics:"गजाननं भूतगणादि सेवितं।\nकपित्थजम्बूफलचारुभक्षणम्॥\n\nउमासुतं शोकविनाशकारकम्।\nनमामि विघ्नेश्वरपादपङ्कजम्॥\n\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव शुभकार्येषु सर्वदा॥\n\nएकदन्तं महाकायं लम्बोदरगजाननम्।\nविघ्ननाशकरं देवं हेरम्बं प्रणमाम्यहम्॥" },
  { slug:"ganpati-mantra", title:"Ganpati Mantra", title_devanagari:"गणपती मंत्र", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"mantra", description:"Ganpati Beej Mantra and Gayatri", source:"Vedas", content_status:"needs_verification", verified:false, published:true, sort_order:37, lyrics:"ॐ गं गणपतये नमः॥\n\nवक्रतुण्डाय हुं।\nएकदन्ताय विद्महे।\nवक्रतुण्डाय धीमहि।\nतन्नो दन्तिः प्रचोदयात्॥\n\nॐ श्री गणेशाय नमः॥\n\nगणानां त्वा गणपतिं हवामहे।\nकविं कवीनामुपमश्रवस्तमम्।\nज्येष्ठराजं ब्रह्मणां ब्रह्मणस्पत।\nआ नः शृण्वन्नूतिभिः सीदसादनम्॥" },
  { slug:"hanuman-chalisa", title:"Hanuman Chalisa", title_devanagari:"हनुमान चालीसा", deity:"Hanuman", category:"hanuman", language:"hindi", type:"chalisa", description:"Complete Hanuman Chalisa by Tulsidas", source:"Tulsidas", content_status:"needs_verification", verified:false, published:true, sort_order:38, lyrics:"श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।\nबरनऊँ रघुबर बिमल जसु, जो दायकु फल चारि॥\n\nबुद्धिहीन तनु जानिके, सुमिरौं पवन-कुमार।\nबल बुधि विद्या देहु मोहिं, हरहु कलेस बिकार॥\n\nजय हनुमान ज्ञान गुन सागर।\nजय कपीस तिहुँ लोक उजागर॥\n\nराम दूत अतुलित बल धामा।\nअंजनि-पुत्र पवनसुत नामा॥\n\nमहाबीर बिक्रम बजरंगी।\nकुमति निवार सुमति के संगी॥\n\nकंचन बरन बिराज सुबेसा।\nकानन कुंडल कुंचित केसा॥\n\nहाथ बज्र औ ध्वजा बिराजै।\nकाँधे मूँज जनेऊ साजै॥\n\nशंकर सुवन केसरी नंदन।\nतेज प्रताप महा जग वंदन॥\n\nविद्यावान गुनी अति चातुर।\nराम काज करिबे को आतुर॥\n\nप्रभु चरित्र सुनिबे को रसिया।\nराम लखन सीता मन बसिया॥\n\nसूक्ष्म रूप धरि सियहिं दिखावा।\nबिकट रूप धरि लंक जरावा॥\n\nभीम रूप धरि असुर संहारे।\nरामचंद्र के काज सँवारे॥\n\nलाय सजीवन लखन जियाए।\nश्रीरघुबीर हरषि उर लाए॥\n\nरघुपति कीन्ही बहुत बड़ाई।\nतुम मम प्रिय भरतहि सम भाई॥\n\nसहस बदन तुम्हरो जस गावैं।\nअस कहि श्रीपति कंठ लगावैं॥\n\nसनकादिक ब्रह्मादि मुनीसा।\nनारद सारद सहित अहीसा॥\n\nजम कुबेर दिगपाल जहाँ ते।\nकवि कोविद कहि सके कहाँ ते॥\n\nतुम उपकार सुग्रीवहिं कीन्हा।\nराम मिलाय राज पद दीन्हा॥\n\nतुम्हरो मंत्र बिभीषण माना।\nलंकेश्वर भए सब जग जाना॥\n\nजुग सहस्र योजन पर भानू।\nलील्यो ताहि मधुर फल जानू॥\n\nप्रभु मुद्रिका मेलि मुख माहीं।\nजलधि लाँघि गए अचरज नाहीं॥\n\nदुर्गम काज जगत के जेते।\nसुगम अनुग्रह तुम्हरे तेते॥\n\nराम दुआरे तुम रखवारे।\nहोत न आज्ञा बिनु पैसारे॥\n\nसब सुख लहै तुम्हारी सरना।\nतुम रक्षक काहू को डरना॥\n\nआपन तेज सम्हारो आपै।\nतीनों लोक हाँक तें काँपै॥\n\nभूत पिशाच निकट नहिं आवै।\nमहाबीर जब नाम सुनावै॥\n\nनासै रोग हरै सब पीरा।\nजपत निरंतर हनुमत बीरा॥\n\nसंकट तें हनुमान छुड़ावै।\nमन क्रम बचन ध्यान जो लावै॥\n\nसब पर राम तपस्वी राजा।\nतिन के काज सकल तुम साजा॥\n\nऔर मनोरथ जो कोई लावै।\nसोई अमित जीवन फल पावै॥\n\nचारों जुग परताप तुम्हारा।\nहै परसिद्ध जगत उजियारा॥\n\nसाधु संत के तुम रखवारे।\nअसुर निकंदन राम दुलारे॥\n\nअष्ट सिद्धि नौ निधि के दाता।\nअस बर दीन जानकी माता॥\n\nराम रसायन तुम्हरे पासा।\nसदा रहो रघुपति के दासा॥\n\nतुम्हरे भजन राम को पावै।\nजनम जनम के दुख बिसरावै॥\n\nअंतकाल रघुवर पुर जाई।\nजहाँ जन्म हरिभक्त कहाई॥\n\nऔर देवता चित्त न धरई।\nहनुमत सेइ सर्व सुख करई॥\n\nसंकट कटै मिटै सब पीरा।\nजो सुमिरै हनुमत बलबीरा॥\n\nजय जय जय हनुमान गोसाईं।\nकृपा करहु गुरुदेव की नाईं॥\n\nजो सत बार पाठ कर कोई।\nछूटहि बंदि महा सुख होई॥\n\nजो यह पढ़ै हनुमान चालीसा।\nहोय सिद्धि साखी गौरीसा॥\n\nतुलसीदास सदा हरि चेरा।\nकीजै नाथ हृदय महँ डेरा॥\n\nपवनतनय संकट हरण, मंगल मूरति रूप।\nराम लखन सीता सहित, हृदय बसहु सुर भूप॥" },
  { slug:"bajrang-baan", title:"Bajrang Baan", title_devanagari:"बजरंग बाण", deity:"Hanuman", category:"hanuman", language:"hindi", type:"stotra", description:"Bajrang Baan - powerful Hanuman stotra", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:39, lyrics:"निश्चय प्रेम प्रतीति ते, विनय करैं सनमान।\nतेहि के कारज सकल शुभ, सिद्ध करैं हनुमान॥\n\nजय हनुमंत संत हितकारी।\nसुन लीजै प्रभु अरज हमारी॥\n\nजन के काज विलंब न कीजै।\nआतुर दौरि महा सुख दीजै॥\n\nजैसे कूदि सिंधु महिपारा।\nसुरसा बदन पैठि विस्तारा॥\n\nआगे जाय लंकिनी रोका।\nमारेहु लात गई सुरलोका॥\n\nजाय विभीषण को सुख दीन्हा।\nसीता निरखि परम पद लीन्हा॥\n\nबाग उजारि सिन्धु महँ बोरा।\nअति आतुर जमकातर तोरा॥\n\nअक्षय कुमार मारि संहारा।\nलूम लपेट लंक को जारा॥\n\nलाह समान लंक जरि गई।\nजय जय धुनि सुरपुर नभ भई॥\n\nअब विलंब केहि कारण स्वामी।\nकृपा करहु उर अंतर्यामी॥\n\nजय जय लखन प्राण के दाता।\nआतुर होइ दुःख हरहु निपाता॥\n\nजय गिरिधर जय जय सुख सागर।\nसुरसमूह समरथ भट नागर॥\n\nॐ हनु हनु हनु हनुमंत हठीले।\nबैरिहि मारु बज्र की कीले॥\n\nगदा बज्र लै बैरिहिं मारो।\nमहाराज प्रभु दास उबारो॥\n\nॐकार हुंकार महाप्रभु धावो।\nबज्र गदा हनु विलंब न लावो॥" },
  { slug:"sankat-mochan-hanumanashtak", title:"Sankat Mochan Hanumanashtak", title_devanagari:"संकट मोचन हनुमानाष्टक", deity:"Hanuman", category:"hanuman", language:"hindi", type:"stotra", description:"Sankat Mochan Hanumanashtak", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:40, lyrics:"बाल समय रवि भक्षि लियो तब, तीनहुँ लोक भयो अँधियारो।\nताहि सों त्रास भयो जग को, यह संकट काहु सों जात न टारो॥\n\nदेवन आनि करी विनती तब, छाँड़ि दियो रवि कष्ट निवारो।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो॥\n\nबालि की त्रास कपीस बसैं गिरि, जात महाप्रभु पंथ निहारो।\nचौंकि महा मुनि साप दियो तब, चाहत कौन विचार विचारो॥\n\nकै द्विज रूप लिवाय महाप्रभु, सो तुम दास के सोक निवारो।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो॥\n\nअंगद के संग लेन गए सिय, खोज कपीस यह बैन उचारो।\nजीवत ना बचिहौ हम सो जु, बिना सुधि लाए इहाँ पगु धारो॥\n\nहेरी थके तट सिंधु सबै तब, लाय सिया-सुधि प्राण उबारो।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो॥\n\nरावण त्रास दई सिय को सब, राक्षसि सों कहि सोक निवारो।\nताहि समय हनुमान महाप्रभु, जाय महा रजनीचर मारो॥\n\nचाहत सीय असोक सों आगि, सो दै प्रभु मुद्रिका सोक निवारो।\nको नहिं जानत है जग में कपि, संकटमोचन नाम तिहारो॥" },
  { slug:"ashtavinayak-ganpati-stavan", title:"Ashtavinayak Ganpati Stavan", title_devanagari:"अष्टविनायक गणपती स्तवन", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"stotra", description:"Ashtavinayak Ganpati Stotra", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:41, lyrics:"ॐ गण गणपतये नमः॥\n\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव शुभकार्येषु सर्वदा॥\n\nएकदन्तं महाकायं लम्बोदरगजाननम्।\nविघ्ननाशकरं देवं हेरम्बं प्रणमाम्यहम्॥\n\nगजाननं भूतगणादि सेवितं।\nकपित्थजम्बूफलचारुभक्षणम्॥\nउमासुतं शोकविनाशकारकम्।\nनमामि विघ्नेश्वरपादपङ्कजम्॥" },
  { slug:"ganesh-panchratna-stotra", title:"Ganesh Panchratna Stotra", title_devanagari:"गणेश पंचरत्न स्तोत्र", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"stotra", description:"Ganesh Panchratna Stotra by Adi Shankaracharya", source:"Adi Shankaracharya", content_status:"needs_verification", verified:false, published:true, sort_order:42, lyrics:"मुदाकरात्तमोदकं सदा विमुक्तिसाधकम्।\nकलाधरावतंसकं विलासिलोकरक्षकम्॥\n\nअनायकैकनायकं विनाशितेभदैत्यकम्।\nनताशुभाशुनाशकं नमामि तं विनायकम्॥\n\nनतेतरातिभीकरं नवोदितार्कभास्वरम्।\nनमत्सुरारिनिर्जरं नताधिकापदुद्धरम्॥\n\nसुरेश्वरं निधीश्वरं गजेश्वरं गणेश्वरम्।\nमहेश्वरं तमाश्रये परात्परं निरन्तरम्॥" },
  { slug:"ganesh-gayatri-mantra", title:"Ganesh Gayatri Mantra", title_devanagari:"गणेश गायत्री मंत्र", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"mantra", description:"Ganesh Gayatri and other Ganpati mantras", source:"Vedas", content_status:"needs_verification", verified:false, published:true, sort_order:43, lyrics:"ॐ एकदन्ताय विद्महे।\nवक्रतुण्डाय धीमहि।\nतन्नो दन्तिः प्रचोदयात्॥\n\nॐ गणाधिपतये नमः॥\n\nॐ विघ्नराजाय नमः॥\n\nॐ लंबोदराय नमः॥\n\nॐ गजाननाय नमः॥\n\nॐ सिद्धिविनायकाय नमः॥" },
  { slug:"sri-ganesh-dhyan-mantra", title:"Sri Ganesh Dhyan Mantra", title_devanagari:"श्री गणेश ध्यान मंत्र", deity:"Ganpati", category:"ganpati", language:"sanskrit", type:"mantra", description:"Ganesh Dhyan Mantra for meditation", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:44, lyrics:"शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम्।\nप्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये॥\n\nवक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।\nनिर्विघ्नं कुरु मे देव शुभकार्येषु सर्वदा॥" },
  { slug:"sri-vishnu-dhyan", title:"Sri Vishnu Dhyan", title_devanagari:"श्री विष्णु ध्यान", deity:"Vishnu", category:"vishnu", language:"sanskrit", type:"stotra", description:"Vishnu Dhyan Shloka for meditation", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:45, lyrics:"शान्ताकारं भुजगशयनं पद्मनाभं सुरेशम्।\nविश्वाधारं गगनसदृशं मेघवर्णं शुभाङ्गम्॥\n\nलक्ष्मीकान्तं कमलनयनं योगिभिर्ध्यानगम्यम्।\nवन्दे विष्णुं भवभयहरं सर्वलोकैकनाथम्॥" },
  { slug:"sri-krishna-prarthana", title:"Sri Krishna Prarthana", title_devanagari:"श्री कृष्ण प्रार्थना", deity:"Krishna", category:"krishna", language:"sanskrit", type:"prayer", description:"Krishna Prarthana and Dhyan Shloka", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:46, lyrics:"कृष्णाय वासुदेवाय हरये परमात्मने।\nप्रणतः क्लेशनाशाय गोविन्दाय नमो नमः॥\n\nवसुदेवसुतं देवं कंसचाणूरमर्दनम्।\nदेवकीपरमानन्दं कृष्णं वन्दे जगद्गुरुम्॥\n\nकरारविन्देन पदारविन्दं।\nमुखारविन्दे विनिवेशयन्तम्॥\n\nवटस्य पत्रस्य पुटे शयानं।\nबालं मुकुन्दं मनसा स्मरामि॥" },
  { slug:"sri-vitthal-namasmaran", title:"Sri Vitthal Namasmaran", title_devanagari:"श्री विठ्ठल नामस्मरण", deity:"Vitthal", category:"vitthal", language:"hindi", type:"mantra", description:"Vitthal Namasmaran - Bhajan/Kirtan style", source:"Warkari Tradition", content_status:"needs_verification", verified:false, published:true, sort_order:47, lyrics:"जय जय राम कृष्ण हरी।\nजय जय राम कृष्ण हरी॥\n\nविठ्ठल विठ्ठल विठ्ठल।\nपांडुरंग हरी॥\n\nराम कृष्ण हरी।\nविठ्ठल रखुमाई॥\n\nज्ञानोबा तुकाराम।\nपांडुरंग हरी॥\n\nजय जय राम कृष्ण हरी॥" },
  { slug:"sri-ram-naam-dhun", title:"Sri Ram Naam Dhun", title_devanagari:"श्री राम नाम धुन", deity:"Rama", category:"ram", language:"hindi", type:"prayer", description:"Ram Naam Dhun - devotional chant", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:48, lyrics:"श्री राम जय राम जय जय राम।\nश्री राम जय राम जय जय राम॥\n\nराम राम राम राम।\nराम राम राम राम॥\n\nसीताराम सीताराम।\nसीताराम सीताराम॥\n\nश्री राम जय राम जय जय राम॥" },
  { slug:"sri-sai-baba-prarthana", title:"Sri Sai Baba Prarthana", title_devanagari:"श्री साई बाबा प्रार्थना", deity:"Sai Baba", category:"sai", language:"hindi", type:"prayer", description:"Sai Baba Prarthana", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:49, lyrics:"ॐ साईं राम।\nॐ साईं राम॥\n\nसबका मालिक एक।\nसबका मालिक एक॥\n\nसाईं नाथ महाराज की जय।\nश्री सच्चिदानंद सद्गुरु साईनाथ महाराज की जय॥\n\nहे साईंनाथ दयाघना।\nचरणी ठेवितो माथा॥\n\nकृपादृष्टी ठेवावी नाथा।\nदूर करावी सर्व व्यथा॥\n\nॐ साईं राम।\nॐ साईं राम॥" },
  { slug:"annapurna-mata-prarthana", title:"Annapurna Mata Prarthana", title_devanagari:"अन्नपूर्णा माता प्रार्थना", deity:"Annapurna", category:"other", language:"sanskrit", type:"prayer", description:"Annapurna Mata Prarthana - prayer for food and nourishment", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:50, lyrics:"अन्नपूर्णे सदापूर्णे शंकरप्राणवल्लभे।\nज्ञानवैराग्यसिद्ध्यर्थं भिक्षां देहि च पार्वति॥\n\nमाता च पार्वती देवी।\nपिता देवो महेश्वरः॥\n\nबान्धवाः शिवभक्ताश्च।\nस्वदेशो भुवनत्रयम्॥\n\nॐ अन्नपूर्णायै नमः॥" },
];

function esc(str) {
  if (str === null || str === undefined) return "NULL";
  return "'" + String(str).replace(/'/g, "''") + "'";
}

for (const a of aartis) {
  const sql = `INSERT INTO aartis (slug, title, title_devanagari, deity, category, language, type, lyrics, transliteration, description, source, source_url, content_status, verified, published, sort_order) VALUES (${esc(a.slug)}, ${esc(a.title)}, ${esc(a.title_devanagari)}, ${esc(a.deity)}, ${esc(a.category)}, ${esc(a.language)}, ${esc(a.type)}, ${esc(a.lyrics)}, NULL, ${esc(a.description)}, ${esc(a.source)}, NULL, ${esc(a.content_status)}, ${a.verified}, ${a.published}, ${a.sort_order}) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, title_devanagari=EXCLUDED.title_devanagari, deity=EXCLUDED.deity, category=EXCLUDED.category, language=EXCLUDED.language, type=EXCLUDED.type, lyrics=EXCLUDED.lyrics, description=EXCLUDED.description, source=EXCLUDED.source, content_status=EXCLUDED.content_status, verified=EXCLUDED.verified, published=EXCLUDED.published, sort_order=EXCLUDED.sort_order;\n`;
  appendFileSync(OUT, sql);
}

console.log(`Appended ${aartis.length} aartis to SQL file (part 2)`);
