import { appendFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "supabase-aartis-seed.sql");

const aartis = [
  { slug:"sukhkarta-dukhharta", title:"Sukhkarta Dukhharta", title_devanagari:"सुखकर्ता दुःखहर्ता", deity:"Ganpati", category:"ganpati", language:"marathi", type:"aarti", description:"Most popular Ganpati Aarti from Maharashtra", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:1, lyrics:"सुखकर्ता दुःखहर्ता वार्ता विघ्नाची।\nनुरवी पुरवी प्रेम कृपा जयाची।\nसर्वांगी सुन्दर उटि शेंदुराची।\nकण्ठी झळके माळ मुक्ताफळांची॥\n\nजय देव जय देव जय मंगलमूर्ति।\nदर्शनमात्रे मनकामना पुरती॥\n\nरत्नखचित फरा तुज गौरीकुमरा।\nचन्दनाची उटि कुंकुमकेशरा।\nहिरे जडित मुकुट शोभतो बरा।\nरुणझुणती नूपुरे चरणी घागरिया॥\n\nजय देव जय देव जय मंगलमूर्ति।\nदर्शनमात्रे मनकामना पुरती॥\n\nलम्बोदर पीताम्बर फणिवर बन्धना।\nसरळ सोण्ड वक्रतुण्ड त्रिनयना।\nदास रामाचा वाट पाहे सदना।\nसंकटी पावावे निर्वाणी रक्षावे सुरवरवन्दना॥\n\nजय देव जय देव जय मंगलमूर्ति।\nदर्शनमात्रे मनकामना पुरती॥" },
  { slug:"jay-ganesh-jay-ganesh-deva", title:"Jay Ganesh Jay Ganesh Deva", title_devanagari:"जय गणेश जय गणेश देवा", deity:"Ganpati", category:"ganpati", language:"hindi", type:"aarti", description:"Popular Hindi Ganpati Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:2, lyrics:"जय गणेश जय गणेश जय गणेश देवा।\nमाता जाकी पार्वती पिता महादेवा॥\n\nएक दंत दयावंत चार भुजा धारी।\nमाथे सिंदूर सोहे मूसे की सवारी॥\n\nजय गणेश जय गणेश जय गणेश देवा।\nमाता जाकी पार्वती पिता महादेवा॥\n\nपान चढ़े फल चढ़े और चढ़े मेवा।\nलड्डुअन का भोग लगे संत करें सेवा॥\n\nजय गणेश जय गणेश जय गणेश देवा।\nमाता जाकी पार्वती पिता महादेवा॥\n\nअंधन को आँख देत कोढ़िन को काया।\nबांझन को पुत्र देत निर्धन को माया॥\n\nजय गणेश जय गणेश जय गणेश देवा।\nमाता जाकी पार्वती पिता महादेवा॥\n\nसूर श्याम शरण आए सफल कीजे सेवा।\nमाता जाकी पार्वती पिता महादेवा॥\n\nजय गणेश जय गणेश जय गणेश देवा।\nमाता जाकी पार्वती पिता महादेवा॥" },
  { slug:"durga-durgat-bhari", title:"Durga Durgat Bhari", title_devanagari:"दुर्गे दुर्घट भारी", deity:"Durga", category:"devi", language:"marathi", type:"aarti", description:"Popular Marathi Durga Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:3, lyrics:"दुर्गे दुर्घट भारी तुजविण संसारी।\nअनाथ नाथे अम्बे करुणा विस्तारी।\nवारी वारी जन्म मरणांते वारी।\nहारी पडलो आता संकट निवारी॥\n\nजय देवी जय देवी महिषासुरमथिनी।\nसुरवर ईश्वर वरदे तारक संजीवनी॥\n\nत्रिभुवन-भुवनी पाहता तुज ऐसी नाही।\nचारी श्रमले परन्तु न बोलवे काही।\nसाही विवाद करिता पडले प्रवाही।\nते तू भक्तालागी पावसि लवलाही॥\n\nजय देवी जय देवी महिषासुरमथिनी।\nसुरवर ईश्वर वरदे तारक संजीवनी॥\n\nप्रसन्न वदने प्रसन्न होसी निजदासा।\nक्लेशांपासुनि सोडवि तोडी भवपाशा।\nअम्बे तुजवाचून कोण पुरविल आशा।\nनरहरी तल्लिन झाला पदपंकजलेशा॥\n\nजय देवी जय देवी महिषासुरमथिनी।\nसुरवर ईश्वर वरदे तारक संजीवनी॥" },
  { slug:"yei-ho-vitthale", title:"Yei Ho Vitthale Maje Mauli Ye", title_devanagari:"येई हो विठ्ठले माझे माऊली ये", deity:"Vitthal", category:"vitthal", language:"marathi", type:"aarti", description:"Popular Vitthal/Pandurang Aarti from Warkari tradition", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:4, lyrics:"येई हो विठ्ठले माझे माऊली ये॥\nनिढळावरी कर ठेऊनी वाट मी पाहे॥ धृ.॥\n\nआलिया गेलिया हातीं धाडी निरोप।\nपंढरपुरी आहे माझा मायबाप॥ १॥\n\nयेई हो विठ्ठले माझे माऊली ये॥\n\nपिंवळा पीतांबर कैसा गगनी झळकला।\nगरुडावरी बैसून माझा कैवारी आला॥ २॥\n\nयेई हो विठ्ठले माझे माऊली ये॥\n\nविठोबाचे राज आम्हां नित्य दिपवाळी।\nविष्णुदास नामा जीवेंभावे ओंवाळी॥ ३॥\n\nयेई हो विठ्ठले माझे माऊली ये॥\n\nअसो नसो भाव आम्हां तुझिया ठायां।\nकृपादृष्टी पाहें माझ्या पंढरीराया॥ ४॥\n\nयेई हो विठ्ठले माझे माऊली ये॥" },
  { slug:"om-jai-shiv-omkara", title:"Om Jai Shiv Omkara", title_devanagari:"ॐ जय शिव ओंकारा", deity:"Shiva", category:"shiva", language:"hindi", type:"aarti", description:"Most popular Shiv Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:5, lyrics:"कर के मध्य कमण्डलुचक्र त्रिशूलधारी।\nसुखकारी दुखहारी जगपालन कारी॥\n\nॐ जय शिव ओंकारा॥\n\nब्रह्मा विष्णु सदाशिव जानत अविवेका।\nप्रणवाक्षर मध्येये तीनों एका॥\n\nॐ जय शिव ओंकारा॥\n\nलक्ष्मी व सावित्री पार्वती संगा।\nपार्वती अर्द्धांगी, शिवलहरी गंगा॥\n\nॐ जय शिव ओंकारा॥\n\nपर्वत सोहैं पार्वती, शंकर कैलासा।\nभांग धतूर का भोजन, भस्मी में वासा॥\n\nॐ जय शिव ओंकारा॥\n\nजटा में गंगा बहत है, गल मुण्डन माला।\nशेष नाग लिपटावत, ओढ़त मृगछाला॥\n\nॐ जय शिव ओंकारा॥\n\nकाशी में विराजे विश्वनाथ, नन्दी ब्रह्मचारी।\nनित उठ दर्शन पावत, महिमा अति भारी॥\n\nॐ जय शिव ओंकारा॥\n\nत्रिगुणस्वामी जी की आरती जो कोइ नर गावे।\nकहत शिवानन्द स्वामी, मनवान्छित फल पावे॥\n\nॐ जय शिव ओंकारा॥" },
  { slug:"aarti-kijai-hanuman-lala-ki", title:"Aarti Kijai Hanuman Lala Ki", title_devanagari:"आरती कीजै हनुमान लला की", deity:"Hanuman", category:"hanuman", language:"hindi", type:"aarti", description:"Most popular Hanuman Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:6, lyrics:"आरती कीजै हनुमान लला की।\nदुष्ट दलन रघुनाथ कला की॥\n\nजाके बल से गिरिवर काँपे।\nरोग दोष जाके निकट न झाँके॥\n\nअंजनि पुत्र महाबलदाई।\nसंतन के प्रभु सदा सहाई॥\n\nदे बीरा रघुनाथ पठाए।\nलंका जारि सिया सुधि लाए॥\n\nलंका सो कोट समुद्र-सी खाई।\nजात पवनसुत बार न लाई॥\n\nलंका जारि असुर संहारे।\nसियारामजी के काज सँवारे॥\n\nलक्ष्मण मूर्छित पड़े सकारे।\nआनि संजीवन प्राण उबारे॥\n\nपैठि पाताल तोरि जम-कारे।\nअहिरावण की भुजा उखारे॥\n\nबाएँ भुजा असुरदल मारे।\nदाएँ भुजा संतजन तारे॥\n\nसुर-नर-मुनि जन आरती उतारें।\nजय जय जय हनुमान उचारें॥\n\nकंचन थार कपूर लौ छाई।\nआरती करत अंजना माई॥\n\nजो हनुमानजी की आरती गावे।\nबसि बैकुण्ठ परम पद पावे॥" },
  { slug:"om-jai-jagdish-hare", title:"Om Jai Jagdish Hare", title_devanagari:"ॐ जय जगदीश हरे", deity:"Vishnu", category:"vishnu", language:"hindi", type:"aarti", description:"Most popular Vishnu/Hari Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:7, lyrics:"ॐ जय जगदीश हरे।\nस्वामी जय जगदीश हरे।\nभक्त जनों के संकट,\nदास जनों के संकट, क्षण में दूर करे॥\n\nॐ जय जगदीश हरे॥\n\nजो ध्यावे फल पावे, दुःख बिनसे मन का।\nसुख सम्पत्ति घर आवे, कष्ट मिटे तन का॥\n\nॐ जय जगदीश हरे॥\n\nमात-पिता तुम मेरे, शरण गहूँ मैं किसकी।\nतुम बिन और न दूजा, आस करूँ मैं जिसकी॥\n\nॐ जय जगदीश हरे॥\n\nतुम पूर्ण परमात्मा, तुम अन्तर्यामी।\nपारब्रह्म परमेश्वर, तुम सबके स्वामी॥\n\nॐ जय जगदीश हरे॥\n\nतुम करुणा के सागर, तुम पालनकर्ता।\nमैं मूरख खल कामी, कृपा करो भर्ता॥\n\nॐ जय जगदीश हरे॥\n\nतुम हो एक अगोचर, सबके प्राणपति।\nकिस विधि मिलूँ दयामय, तुमको मैं कुमति॥\n\nॐ जय जगदीश हरे॥\n\nदीनबन्धु दुःखहर्ता, ठाकुर तुम मेरे।\nअपने हाथ उठाओ, द्वार पड़ा तेरे॥\n\nॐ जय जगदीश हरे॥\n\nविषय विकार मिटाओ, पाप हरो देवा।\nश्रद्धा भक्ति बढ़ाओ, संतन की सेवा॥\n\nॐ जय जगदीश हरे॥" },
  { slug:"om-jai-ambe-gauri", title:"Om Jai Ambe Gauri", title_devanagari:"ॐ जय अम्बे गौरी", deity:"Ambe Gauri", category:"devi", language:"hindi", type:"aarti", description:"Popular Ambe Gauri/Parvati Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:8, lyrics:"ॐ जय अम्बे गौरी, मैया जय श्यामा गौरी।\nतुमको निशदिन ध्यावत, हरि ब्रह्मा शिवरी॥\n\nॐ जय अम्बे गौरी॥\n\nमाँग सिंदूर विराजत, टीको मृगमद को।\nउज्ज्वल से दोउ नैना, चन्द्रवदन नीको॥\n\nॐ जय अम्बे गौरी॥\n\nकनक समान कलेवर, रक्ताम्बर राजै।\nरक्तपुष्प गल माला, कण्ठन पर साजै॥\n\nॐ जय अम्बे गौरी॥\n\nकेहरि वाहन राजत, खड्ग कृपाण धारी।\nसुर-नर-मुनिजन सेवत, तिनके दुःखहारी॥\n\nॐ जय अम्बे गौरी॥\n\nकानन कुण्डल शोभित, नासाग्रे मोती।\nकोटिक चन्द्र दिवाकर, राजत सम ज्योती॥\n\nॐ जय अम्बे गौरी॥\n\nशुम्भ निशुम्भ बिदारे, महिषासुर घाती।\nधूम्र विलोचन नैना, निशदिन मदमाती॥\n\nॐ जय अम्बे गौरी॥\n\nचण्ड-मुण्ड संहारे, शोणित बीज हरे।\nमधु कैटभ दोउ मारे, सुर भयहीन करे॥\n\nॐ जय अम्बे गौरी॥\n\nब्रह्माणी रुद्राणी, तुम कमला रानी।\nआगम निगम बखानी, तुम शिव पटरानी॥\n\nॐ जय अम्बे गौरी॥" },
  { slug:"om-jai-lakshmi-mata", title:"Om Jai Lakshmi Mata", title_devanagari:"ॐ जय लक्ष्मी माता", deity:"Lakshmi", category:"devi", language:"hindi", type:"aarti", description:"Most popular Lakshmi Aarti", source:"Traditional", content_status:"verified", verified:true, published:true, sort_order:9, lyrics:"ॐ जय लक्ष्मी माता, मैया जय लक्ष्मी माता।\nतुमको निशदिन सेवत, हरि विष्णु विधाता॥\n\nॐ जय लक्ष्मी माता॥\n\nउमा, रमा, ब्रह्माणी, तुम ही जग माता।\nसूर्य-चन्द्रमा ध्यावत, नारद ऋषि गाता॥\n\nॐ जय लक्ष्मी माता॥\n\nदुर्गा रूप निरंजनी, सुख सम्पत्ति दाता।\nजो कोई तुमको ध्यावत, ऋद्धि-सिद्धि धन पाता॥\n\nॐ जय लक्ष्मी माता॥\n\nतुम पाताल निवासिनी, तुम ही शुभदाता।\nकर्म-प्रभाव प्रकाशिनी, भवनिधि की त्राता॥\n\nॐ जय लक्ष्मी माता॥\n\nजिस घर तुम रहतीं, सब सद्गुण आता।\nसब सम्भव हो जाता, मन नहीं घबराता॥\n\nॐ जय लक्ष्मी माता॥\n\nतुम बिन यज्ञ न होते, वस्त्र न कोई पाता।\nखान-पान का वैभव, तुमसे ही आता॥\n\nॐ जय लक्ष्मी माता॥\n\nशुभ गुण मन्दिर सुन्दर, क्षीरोदधि जाता।\nरत्न चतुर्दश तुम बिन, कोई नहीं पाता॥\n\nॐ जय लक्ष्मी माता॥\n\nधूप दीप फल मेवा, माता स्वीकार करो।\nज्ञान प्रकाश करो माता, त्रिविध ताप हरो॥\n\nॐ जय लक्ष्मी माता॥" },
  { slug:"sri-ramchandra-kripalu", title:"Sri Ramchandra Kripalu Bhaju Man", title_devanagari:"श्री रामचन्द्र कृपालु भजु मन", deity:"Rama", category:"ram", language:"sanskrit", type:"aarti", description:"Famous Ram Aarti by Tulsidas", source:"Tulsidas", content_status:"verified", verified:true, published:true, sort_order:10, lyrics:"श्री रामचन्द्र कृपालु भजु मन, हरण भवभय दारुणम्।\nनव कंज लोचन, कंज मुख, कर कंज, पद कंजारुणम्॥\n\nकंदर्प अगणित अमित छवि, नव नील नीरद सुन्दरम्।\nपटपीत मानहुँ तड़ित रुचि शुचि, नौमि जनक सुतावरम्॥\n\nभजु दीनबन्धु दिनेश दानव, दैत्यवंश निकन्दनम्।\nरघुनन्द आनंदकन्द, कौशलचन्द दशरथ नन्दनम्॥\n\nसिर मुकुट कुण्डल तिलक चारु, उदारु अंग विभूषणम्।\nआजानुभुज शर चाप धर, संग्राम जित खरदूषणम्॥\n\nइति वदति तुलसीदास, शंकर-शेष-मुनि-मन-रंजनम्।\nमम हृदय कंज निवास कुरु, कामादि खलदल गंजनम्॥\n\nमनु जाहिं राचेउ मिलिहि सो बरु, सहज सुन्दर साँवरो।\nकरुणानिधान सुजान सीलु, सनेहु जानत रावरो॥\n\nएहि भाँति गौरी असीस सुनि, सिय सहित हियँ हरषीं अली।\nतुलसी भवानिहि पूजि पुनि पुनि, मुदित मन मंदिर चली॥" },
  { slug:"ganpati-ki-seva-mangal-meva", title:"Ganpati Ki Seva Mangal Meva", title_devanagari:"गणपति की सेवा मंगल मेवा", deity:"Ganpati", category:"ganpati", language:"hindi", type:"aarti", description:"Ganpati Seva Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:11, lyrics:"गणपति की सेवा मंगल मेवा।\nसेवा से सब विघ्न टरें, तीन लोक के देवा॥\n\nधूप दीप नैवेद्य आरती, पूजन करैं गणेशा।\nसुमिरन करैं जो तुम्हरो, ताको मिले हमेशा॥\n\nगणपति की सेवा मंगल मेवा।\nसेवा से सब विघ्न टरें, तीन लोक के देवा॥\n\nलड्डुअन का भोग लगावैं, मोदक अति मनभावन।\nभक्त जनों की आस पुरावैं, विघ्न विनाशन पावन॥\n\nगणपति की सेवा मंगल मेवा।\nसेवा से सब विघ्न टरें, तीन लोक के देवा॥" },
  { slug:"aarti-gajbadan-vinayak-ki", title:"Aarti Gajbadan Vinayak Ki", title_devanagari:"आरती गजबदन विनायक की", deity:"Ganpati", category:"ganpati", language:"hindi", type:"aarti", description:"Short Ganpati Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:12, lyrics:"आरती गजबदन विनायक की।\nसुर मुनि पूजत चरण नायक की॥\n\nएकदंत गजवदन विराजत।\nकर में मोदक सदा सुहाजत॥\n\nजय जय जय गणराज गणपति।\nमंगल मूर्ति विघ्न विनाशक॥" },
  { slug:"shendur-lal-chadhayo", title:"Shendur Lal Chadhayo", title_devanagari:"शेंदूर लाल चढायो", deity:"Ganpati", category:"ganpati", language:"hindi", type:"aarti", description:"Popular Ganpati Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:13, lyrics:"शेंदूर लाल चढायो अच्छा गजमुखको।\nदोंदिल लाल बिराजे सुत गौरिहरको॥\n\nहाथ लिये गुडलड्डु साईं सुरवरको।\nमहिमा कहे न जाय लागत हूँ पायको॥\n\nजय देव जय देव जय मंगलमूर्ति।\nदर्शनमात्रे मनकामना पुरती॥\n\nअष्टौ सिद्धि दासी संकटको बैरी।\nविघ्नविनाशन मंगल मूरत अधिकारी॥\n\nजय देव जय देव जय मंगलमूर्ति।\nदर्शनमात्रे मनकामना पुरती॥" },
  { slug:"ghalin-lotangan", title:"Ghalin Lotangan", title_devanagari:"घालीन लोटांगण", deity:"Ganpati", category:"ganpati", language:"marathi", type:"aarti", description:"Traditional Ganpati Aarti with Vedic mantras", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:14, lyrics:"घालीन लोटांगण वंदीन चरण।\nडोळ्यांनी पाहीन रूप तुझे॥\nप्रेमें आलिंगीन आनंदे पूजीन।\nभावे ओवाळीन म्हणे नामा॥\n\nत्वमेव माता च पिता त्वमेव।\nत्वमेव बंधुश्च सखा त्वमेव।\nत्वमेव विद्या द्रविणं त्वमेव।\nत्वमेव सर्वं मम देव देव॥\n\nकायेन वाचा मनसेंद्रियैर्वा।\nबुद्ध्यात्मना वा प्रकृतेः स्वभावात्।\nकरोमि यद्यत् सकलं परस्मै।\nनारायणायेति समर्पयामि॥\n\nअच्युतं केशवं रामनारायणम्।\nकृष्णदामोदरं वासुदेवं हरिम्।\nश्रीधरं माधवं गोपिकावल्लभम्।\nजानकीनायकं रामचंद्रं भजे॥" },
  { slug:"mantra-pushpanjali", title:"Mantra Pushpanjali", title_devanagari:"मंत्र पुष्पांजली", deity:"Multi", category:"other", language:"sanskrit", type:"prayer", description:"Vedic Mantra Pushpanjali for worship", source:"Vedas", content_status:"needs_verification", verified:false, published:true, sort_order:15, lyrics:"ॐ यज्ञेन यज्ञमयजन्त देवास्तानि धर्माणि प्रथमान्यासन्।\nते ह नाकं महिमानः सचन्त यत्र पूर्वे साध्याः सन्ति देवाः॥\n\nॐ राजाधिराजाय प्रसह्यसाहिने।\nनमो वयं वैश्रवणाय कुर्महे।\nस मे कामान् कामकामाय मह्यं।\nकामेश्वरो वैश्रवणो ददातु॥\n\nकुबेराय वैश्रवणाय महाराजाय नमः॥\n\nॐ स्वस्ति।\nसाम्राज्यं भौज्यं स्वाराज्यं वैराज्यं।\nपारमेष्ठ्यं राज्यं महाराज्यमाधिपत्यमयं॥" },
  { slug:"jayati-mangalagar", title:"Jayati Mangalagar", title_devanagari:"जयति मंगलागार", deity:"Rama", category:"ram", language:"hindi", type:"aarti", description:"Short Ram Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:16, lyrics:"जयति मंगलागार, संसार भारापहार।\nदशरथ राजकुमार, रघुकुल तिलक॥\n\nजय जय श्रीराम॥\n\nदीनदयाल दयासागर, भक्तन हितकारी।\nसंकट मोचन नाम तुम्हारा, शरण पड़े संसारी॥\n\nजय जय श्रीराम॥" },
  { slug:"om-jai-hanumat-veera", title:"Om Jai Hanumat Veera", title_devanagari:"ॐ जय हनुमत वीरा", deity:"Hanuman", category:"hanuman", language:"hindi", type:"aarti", description:"Short Hanuman Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:17, lyrics:"ॐ जय हनुमत वीरा, स्वामी जय हनुमत वीरा।\nसंकट मोचन स्वामी, भक्तन हितकारी॥\n\nॐ जय हनुमत वीरा॥\n\nरामदूत बलधामा, अंजनि के लाला।\nमहाबली महावीरा, तुम जग रखवाला॥\n\nॐ जय हनुमत वीरा॥\n\nलंका जारि सियासुधि लाए।\nराम काज तुम कीन्हे॥\n\nॐ जय हनुमत वीरा॥" },
  { slug:"vishnu-aarti-om-jai-jagdish", title:"Vishnu Aarti - Om Jai Jagdish Hare", title_devanagari:"विष्णु आरती", deity:"Vishnu", category:"vishnu", language:"hindi", type:"aarti", description:"Vishnu Aarti - shorter version", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:18, lyrics:"ॐ जय जगदीश हरे।\nस्वामी जय जगदीश हरे।\nभक्त जनों के संकट,\nदास जनों के संकट, क्षण में दूर करे॥\n\nजो ध्यावे फल पावे, दुःख बिनसे मन का।\nसुख सम्पत्ति घर आवे, कष्ट मिटे तन का॥\n\nमात-पिता तुम मेरे, शरण गहूँ मैं किसकी।\nतुम बिन और न दूजा, आस करूँ मैं जिसकी॥\n\nतुम पूर्ण परमात्मा, तुम अन्तर्यामी।\nपारब्रह्म परमेश्वर, तुम सबके स्वामी॥" },
  { slug:"santoshi-mata-aarti", title:"Santoshi Mata Aarti", title_devanagari:"संतोषी माता आरती", deity:"Santoshi Mata", category:"devi", language:"hindi", type:"aarti", description:"Santoshi Mata Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:19, lyrics:"जय संतोषी माता, मैया जय संतोषी माता।\nअपने सेवक जन की, सुख सम्पत्ति दाता॥\n\nसुंदर चीर सुनहरी, माँ धारण कीन्हो।\nहीरा पन्ना जड़ित मुकुट, शीश धर लीन्हो॥\n\nजय संतोषी माता॥\n\nगेरू लाल छटा छबि, बदन कमल सोहे।\nमंद हँसत करुणामयी, त्रिभुवन मन मोहे॥\n\nजय संतोषी माता॥\n\nस्वर्ण सिंहासन बैठी, चँवर डुलावे।\nधूप दीप नैवेद्य आरती, भक्त चढ़ावे॥\n\nजय संतोषी माता॥" },
  { slug:"satyanarayan-aarti", title:"Satyanarayan Aarti", title_devanagari:"सत्यनारायण आरती", deity:"Satyanarayan", category:"vishnu", language:"hindi", type:"aarti", description:"Satyanarayan Puja Aarti", source:"Traditional", content_status:"needs_verification", verified:false, published:true, sort_order:20, lyrics:"जय लक्ष्मी रमणा, स्वामी जय लक्ष्मी रमणा।\nसत्यनारायण स्वामी, जन पातक हरणा॥\n\nजय लक्ष्मी रमणा॥\n\nरत्न जड़ित सिंहासन, अद्भुत छवि राजे।\nनारद करत निरंतर, घंटा ध्वनि बाजे॥\n\nजय लक्ष्मी रमणा॥\n\nप्रगट भए कलिकारण, द्विज को दरस दियो।\nबूढ़ो ब्राह्मण बनकर, कंचन महल कियो॥\n\nजय लक्ष्मी रमणा॥\n\nदुर्बल भील कठोर, जिन पर कृपा करी।\nचंद्रचूड़ एक राजा, तिनकी विपत्ति हरी॥\n\nजय लक्ष्मी रमणा॥" },
];

function esc(str) {
  if (str === null || str === undefined) return "NULL";
  return "'" + String(str).replace(/'/g, "''") + "'";
}

for (const a of aartis) {
  const sql = `INSERT INTO aartis (slug, title, title_devanagari, deity, category, language, type, lyrics, transliteration, description, source, source_url, content_status, verified, published, sort_order) VALUES (${esc(a.slug)}, ${esc(a.title)}, ${esc(a.title_devanagari)}, ${esc(a.deity)}, ${esc(a.category)}, ${esc(a.language)}, ${esc(a.type)}, ${esc(a.lyrics)}, ${esc(a.transliteration || null)}, ${esc(a.description)}, ${esc(a.source)}, ${esc(a.source_url || null)}, ${esc(a.content_status)}, ${a.verified}, ${a.published}, ${a.sort_order}) ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, title_devanagari=EXCLUDED.title_devanagari, deity=EXCLUDED.deity, category=EXCLUDED.category, language=EXCLUDED.language, type=EXCLUDED.type, lyrics=EXCLUDED.lyrics, description=EXCLUDED.description, source=EXCLUDED.source, content_status=EXCLUDED.content_status, verified=EXCLUDED.verified, published=EXCLUDED.published, sort_order=EXCLUDED.sort_order;\n`;
  appendFileSync(OUT, sql);
}

console.log(`Appended ${aartis.length} aartis to SQL file (part 1)`);
